# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: aws-network-firewall
  description: This component is responsible for provisioning AWS Network Firewall resources, including Network Firewall, firewall policy, rule groups, and logging configuration
  homepage: https://cloudposse.com/accelerate
  topics: terraform, terraform-component







